name: ccp_user_app
description: CryptoClock Pro — set up and control your display over WiFi LAN.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  multicast_dns: ^0.3.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  image_picker: ^1.1.0
  image: ^4.2.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
