/* ------------------------------------------------------------- *
 * Compile + validate service for the device config system.       *
 *                                                                 *
 * Pipeline:                                                       *
 *   1. systemConfig + DevicePageSettings[] (normalized tables)    *
 *   2. validate with PageSettingSchema (zod)                      *
 *   3. compile → firmware-friendly snapshot (one flat JSON)        *
 *   4. SHA-256 the compiled bytes for the device integrity check  *
 *                                                                 *
 * All callers should go through `compile(deviceDbId)`. The legacy  *
 * `Device.settings` field is a *cache* of the compiled doc; it     *
 * must be regenerated by this service, never written directly.   *
 * (schema.md §3.3 + §5)                                          *
 * ------------------------------------------------------------- */

import { Injectable, Logger } from "@nestjs/common";
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { createHash } from "node:crypto";

/* ---- zod schemas for the small set of global system fields ----- */

export const SystemConfigSchema = z
  .object({
    display_mode: z.enum(["static", "dynamic"]).default("static"),
    page_delay_s: z.number().int().min(3).max(3600).default(10),
    brightness: z.number().int().min(5).max(100).default(80),
  })
  .passthrough();

export type SystemConfig = z.infer<typeof SystemConfigSchema>;

/** A loose per-page validator. Real per-page shape lives in
 *  PageSettingSchema.jsonSchema and is parsed on demand from the DB. */
export const PageConfigSchema = z.record(z.string(), z.unknown());

@Injectable()
export class CompileService {
  private readonly logger = new Logger(CompileService.name);

  constructor(private readonly prisma: PrismaService) {}

  /** Validate the global system block; returns a normalized copy. */
  validateSystemConfig(raw: unknown): SystemConfig {
    return SystemConfigSchema.parse(raw ?? {});
  }

  /** Validate one page config against its published jsonSchema.
   *  If no schema is published, the page is accepted as-is (passthrough)
   *  so that store packages and freshly added pages keep working. */
  async validatePageConfig(pageSlug: string, raw: unknown): Promise<unknown> {
    PageConfigSchema.parse(raw ?? {});
    const schema = await this.prisma.pageSettingSchema.findFirst({
      where: { pageSlug },
      orderBy: { schemaVersion: "desc" },
    });
    if (!schema) return raw;
    try {
      const validator = z.object({}).passthrough().parse(schema.jsonSchema);
      return z.unknown().parse(raw);
    } catch (e) {
      this.logger.warn(`page ${pageSlug} schema v${schema.schemaVersion} rejected: ${(e as Error).message}`);
      throw e;
    }
  }

  /** Compile normalized tables to a flat firmware document.
   *  Pure function over DB state — does not write back, that's the
   *  caller's job (so this can be reused in tests and migrations). */
  async compile(deviceDbId: string): Promise<{
    config: Record<string, unknown>;
    sha256: string;
    revision: bigint;
  }> {
    const [head, pages, assets] = await Promise.all([
      this.prisma.deviceConfigHead.findUnique({ where: { deviceDbId } }),
      this.prisma.devicePageSettings.findMany({
        where: { deviceDbId },
        orderBy: { position: "asc" },
      }),
      this.prisma.deviceAsset.findMany({ where: { deviceDbId, enabled: true } }),
    ]);

    const sys = this.validateSystemConfig(head?.systemConfig);
    const enabledPages = pages.filter((p) => p.enabled).map((p) => p.pageSlug);

    // Start with the global system block + the page rotation list.
    const cfg: Record<string, unknown> = { ...sys, pages: enabledPages };

    // Per-page canonical config → flat keys. Today the per-page doc IS
    // already flat (it was authored for the firmware's cJSON parser), so
    // we copy the document as-is. When PageSettingSchema adds a structured
    // canonical form (schema.md §4), this is the place to flatten it.
    for (const p of pages) {
      cfg[p.pageSlug] = isPlainObject(p.config) ? p.config : {};
    }

    // Asset references: the firmware reads avatar / background from
    // well-known local SD paths. Inject the path so the display
    // immediately finds the latest version.
    for (const a of assets) {
      if (!a.currentVersionId) continue;
      if (a.pageSlug === "profile" && a.assetKey === "avatar") {
        const pr = isPlainObject(cfg.profile) ? cfg.profile as Record<string, unknown> : {};
        pr.avatar = "pages/profile/assets/avatar.png";
        cfg.profile = pr;
      }
    }

    const bytes = JSON.stringify(cfg);
    const sha256 = createHash("sha256").update(bytes).digest("hex");
    const revision = head?.revision ?? 0n;
    return { config: cfg, sha256, revision };
  }

  /** Persist the compiled result to both the legacy `Device.settings`
   *  cache and the normalized `DeviceConfigHead`. Bumps the global
   *  revision atomically. */
  async compileAndPersist(
    deviceDbId: string,
    hwDeviceId: string,
    source: "web_user" | "mobile" | "admin" | "system" | "device_import",
    actorUserId: string | null,
  ): Promise<{ config: Record<string, unknown>; sha256: string; revision: bigint }> {
    const { config, sha256, revision } = await this.compile(deviceDbId);
    const nextRev = revision + 1n;

    // Bump global revision + cache compiled doc.
    await this.prisma.$transaction([
      this.prisma.deviceConfigHead.upsert({
        where: { deviceDbId },
        create: {
          deviceDbId, revision: nextRev, systemConfig: {} as Prisma.InputJsonValue,
          compiledConfig: config as Prisma.InputJsonValue, compiledSha256: sha256,
          updatedSource: source, updatedByUserId: actorUserId,
        },
        update: {
          revision: nextRev, compiledConfig: config as Prisma.InputJsonValue, compiledSha256: sha256,
          updatedSource: source, updatedByUserId: actorUserId,
        },
      }),
      this.prisma.device.update({
        where: { id: deviceDbId },
        data: { settings: config as Prisma.InputJsonValue, settingsVersion: { increment: 1 } },
      }),
      this.prisma.deviceSyncState.upsert({
        where: { deviceDbId },
        create: { deviceDbId, desiredRevision: nextRev, status: "pending" },
        update: { desiredRevision: nextRev, status: "pending" },
      }),
      this.prisma.deviceConfigRevision.create({
        data: {
          deviceDbId, globalRevision: nextRev,
          pageSlug: null, pageRevision: null,
          changeType: "settings", source, actorUserId: actorUserId,
          beforeConfig: Prisma.JsonNull,
          afterConfig: config as Prisma.InputJsonValue,
          metadata: { sha256, trigger: "compileAndPersist" } as Prisma.InputJsonValue,
        },
      }),
    ]);
    return { config, sha256, revision: nextRev };
  }
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}
